version: "2"
services:

  shop:
    image: dnhsoft/shopware:5.6.1
    links:
      - mysql:db
      - mailhog
    ports:
      - "8002:80"
#    volumes:
#      - "./volumes/shop/log:/shopware/var/log"
#      - "./volumes/shop/files:/shopware/files"
#      - "./volumes/shop/media:/shopware/media"
    env_file:
      - shop-variables-local.env

  mysql:
    image: mysql:5.7
 #   volumes:
 #     - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Europe/Berlin

  pma:
    image: phpmyadmin/phpmyadmin:4.8
    links:
      - mysql:db
    ports:
      - "8003:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: 123456
      TZ: Europe/Berlin
      
  mailhog:
    image: mailhog/mailhog
    expose:
      - "1025"
      - "8025"
    ports:
      - "8025:8025"
    environment:
      TZ: Europe/Berlin